# All distance units in mm, durations in seconds

linuxcnc_folder: "linuxCNC/team303_machine.ini"
linuxcnc_timeout: 120.0

mqtt_broker_ip: "192.168.0.1"
mqtt_received_topic: "test/topic"
mqtt_error_topic: "test/error"
mqtt_complete_topic: "test/complete"

ds_amount_per: 4
ds_rows: 7
ds_cols: 4

gripper_axis: "A"
gripper_down: 10.0
gripper_up: 9.0

clean_plate_axis: "B"
clean_plate_distance: 200.0
